name: Metrics
on:
  # Schedule updates (every hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run it manually from the Actions tab
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: EmmanuelBitancor
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          
          # This makes the image wider and tidier (fixes "too large" height)
          config_twocolumn: yes

          # Plugins - This adds your Top Languages inside the card
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
